import 'package:flutter/material.dart';
import 'job_model.dart';

class JobDummyData {
  static const List<JobCategory> categories = [
    JobCategory(
      id: 'dev',
      title: 'Software Dev',
      icon: Icons.code_rounded,
      jobsCount: 142,
      themeColor: Color(0xFF2563EB), // Blue
    ),
    JobCategory(
      id: 'design',
      title: 'UI/UX Design',
      icon: Icons.palette_outlined,
      jobsCount: 88,
      themeColor: Color(0xFF9333EA), // Purple
    ),
    JobCategory(
      id: 'data',
      title: 'Data & AI',
      icon: Icons.insights_rounded,
      jobsCount: 65,
      themeColor: Color(0xFF0D9488), // Teal
    ),
    JobCategory(
      id: 'product',
      title: 'Product Mgmt',
      icon: Icons.dashboard_customize_outlined,
      jobsCount: 47,
      themeColor: Color(0xFFEA580C), // Orange
    ),
    JobCategory(
      id: 'marketing',
      title: 'Marketing',
      icon: Icons.campaign_outlined,
      jobsCount: 93,
      themeColor: Color(0xFFE11D48), // Rose
    ),
    JobCategory(
      id: 'finance',
      title: 'Finance & Ops',
      icon: Icons.account_balance_outlined,
      jobsCount: 39,
      themeColor: Color(0xFF16A34A), // Green
    ),
  ];

  static const List<Job> allJobs = [
    Job(
      id: 'job-1',
      title: 'Senior Flutter Developer',
      company: 'TechNova Solutions',
      companyLogoUrl: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=150',
      location: 'Bangalore, Karnataka (Remote)',
      categoryId: 'dev',
      salary: '₹14 - ₹22 LPA',
      jobType: 'Full Time',
      workplaceType: 'Remote',
      experienceLevel: 'Senior (4-7 yrs)',
      postedAgo: '2 hours ago',
      isFeatured: true,
      cardColor: Color(0xFF1E3A8A),
      skills: ['Flutter', 'Dart', 'REST APIs', 'State Management', 'CI/CD'],
      description:
          'TechNova is looking for a Senior Flutter Developer to lead the mobile architecture for our next-generation enterprise productivity suite. You will build highly responsive, smooth, and scalable mobile and web applications.',
      responsibilities: [
        'Design and implement high-performance cross-platform Flutter applications.',
        'Collaborate with UI/UX designers and product managers to define feature specs.',
        'Write clean, maintainable, testable code adhering to best practices.',
        'Optimize app performance, startup times, and memory consumption.',
        'Mentor junior engineers and lead code reviews.',
      ],
      requirements: [
        '4+ years of solid experience in mobile development with 2+ years in Flutter & Dart.',
        'Deep understanding of state management architectures and widget lifecycles.',
        'Experience releasing apps to Google Play Store & Apple App Store.',
        'Familiarity with native platform channels (Android Kotlin/Java & iOS Swift).',
        'Strong debugging and performance profiling abilities.',
      ],
      benefits: [
        '100% Remote flexibility with home office setup reimbursement',
        'Comprehensive health insurance for family (₹5 Lakh cover)',
        'Annual ₹30,000 learning & conference allowance',
        'Generous paid time off & flexible holidays',
        'Annual performance appraisal and retention bonuses',
      ],
    ),
    Job(
      id: 'job-2',
      title: 'Lead Product Designer (UI/UX)',
      company: 'PixelCraft Studio',
      companyLogoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150',
      location: 'Hyderabad, Telangana (Hybrid)',
      categoryId: 'design',
      salary: '₹16 - ₹25 LPA',
      jobType: 'Full Time',
      workplaceType: 'Hybrid',
      experienceLevel: 'Lead (6+ yrs)',
      postedAgo: '5 hours ago',
      isFeatured: true,
      cardColor: Color(0xFF581C87),
      skills: ['Figma', 'Design Systems', 'User Research', 'Prototyping', 'Interaction Design'],
      description:
          'PixelCraft Studio is seeking a Lead UI/UX Product Designer to helm the design systems and user journey for top-tier fintech and SaaS consumer applications.',
      responsibilities: [
        'Lead end-to-end design lifecycle from discovery to pixel-perfect handoffs.',
        'Evolve and maintain an accessible, scalable multi-brand design system.',
        'Conduct qualitative and quantitative user interviews and usability tests.',
        'Partner directly with VP of Product and Lead Developers.',
      ],
      requirements: [
        '6+ years of digital product design experience with a strong online portfolio.',
        'Mastery of Figma, advanced component variants, and interactive prototyping.',
        'Demonstrated track record of designing complex workflows simplified for users.',
        'Strong communication and executive presentation skills.',
      ],
      benefits: [
        'Hybrid working policy with modern office amenities',
        'Employee stock option plan (ESOP)',
        'Medical insurance with mental wellness consultations',
        'Apple MacBook Pro setup and ergonomics equipment',
      ],
    ),
    Job(
      id: 'job-3',
      title: 'Machine Learning Engineer',
      company: 'Aether AI Labs',
      companyLogoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150',
      location: 'Pune, Maharashtra / Remote',
      categoryId: 'data',
      salary: '₹15 - ₹24 LPA',
      jobType: 'Full Time',
      workplaceType: 'Remote',
      experienceLevel: 'Mid-Senior (3-5 yrs)',
      postedAgo: '1 day ago',
      isFeatured: true,
      cardColor: Color(0xFF134E4A),
      skills: ['Python', 'PyTorch', 'Transformers', 'LLMs', 'Docker', 'Kubernetes'],
      description:
          'Join Aether AI Labs to build next-generation foundational model inference engines and retrieval-augmented intelligence tools.',
      responsibilities: [
        'Fine-tune and deploy transformer-based models for production scale.',
        'Build low-latency inference pipelines and evaluation benchmarks.',
        'Collaborate with data engineers to curate and sanitize large-scale datasets.',
      ],
      requirements: [
        'B.Tech / M.Tech in Computer Science, AI, Mathematics or related field.',
        'Proficiency in Python, PyTorch, Hugging Face ecosystem, and cloud compute.',
        'Experience building low-latency REST/gRPC inference servers.',
      ],
      benefits: [
        'Competitive stock options & joining bonus',
        'Generous annual cloud GPU research budget',
        'Health and term life insurance',
      ],
    ),
    Job(
      id: 'job-4',
      title: 'Senior Product Manager',
      company: 'CloudScale Inc.',
      companyLogoUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=150',
      location: 'Gurugram, NCR',
      categoryId: 'product',
      salary: '₹18 - ₹28 LPA',
      jobType: 'Full Time',
      workplaceType: 'On-site',
      experienceLevel: 'Senior (5+ yrs)',
      postedAgo: '1 day ago',
      isFeatured: false,
      cardColor: Color(0xFF7C2D12),
      skills: ['Product Strategy', 'Roadmapping', 'Agile/Scrum', 'Data Analytics', 'A/B Testing'],
      description:
          'CloudScale is looking for a metrics-driven Senior Product Manager to drive growth and user retention for our cloud infrastructure automation platform.',
      responsibilities: [
        'Define the multi-quarter product roadmap and feature backlog.',
        'Analyze user engagement funnels and prioritize high-ROI initiatives.',
        'Bridge business needs with software engineering velocity.',
      ],
      requirements: [
        '5+ years of PM experience in B2B SaaS or developer tools.',
        'Proven ability to translate complex customer challenges into simple user experiences.',
        'Familiarity with SQL and product analytics platforms.',
      ],
      benefits: [
        'Subsidized daily lunch and team meals',
        'Provident fund (EPF) and gratuity benefits',
        'Commuter allowance and wellness subsidy',
      ],
    ),
    Job(
      id: 'job-5',
      title: 'Digital Marketing Strategist',
      company: 'Vanguard Growth Agency',
      companyLogoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=150',
      location: 'Mumbai, Maharashtra (Remote)',
      categoryId: 'marketing',
      salary: '₹6 - ₹9.5 LPA',
      jobType: 'Full Time',
      workplaceType: 'Remote',
      experienceLevel: 'Mid Level (2-4 yrs)',
      postedAgo: '2 days ago',
      isFeatured: false,
      cardColor: Color(0xFF881337),
      skills: ['SEO/SEM', 'Google Ads', 'Content Strategy', 'HubSpot', 'Conversion Optimization'],
      description:
          'Drive customer acquisition and multi-channel campaigns for fast-scaling startups across India and global accounts.',
      responsibilities: [
        'Plan, launch, and optimize high-converting paid search and social campaigns.',
        'Analyze campaign performance and generate weekly executive insights.',
        'Conduct keyword research and optimize landing page copy.',
      ],
      requirements: [
        '2-4 years managing substantial ad budgets on Google Ads and LinkedIn Ads.',
        'Deep understanding of attribution modeling and funnel analytics.',
      ],
      benefits: [
        'Flexible remote working hours',
        'Quarterly performance-based incentives',
        'Annual company retreat and get-togethers',
      ],
    ),
    Job(
      id: 'job-6',
      title: 'Financial Analyst & Operations',
      company: 'Apex Capital Partners',
      companyLogoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150',
      location: 'New Delhi, India',
      categoryId: 'finance',
      salary: '₹5 - ₹8 LPA',
      jobType: 'Full Time',
      workplaceType: 'On-site',
      experienceLevel: 'Entry-Mid (1-3 yrs)',
      postedAgo: '3 days ago',
      isFeatured: false,
      cardColor: Color(0xFF14532D),
      skills: ['Financial Modeling', 'Excel / Sheets', 'Forecasting', 'Valuation', 'PowerBI'],
      description:
          'Analyze market trends, forecast portfolio financial performance, and prepare comprehensive evaluation reports for investment decision-making.',
      responsibilities: [
        'Build three-statement financial models and cash-flow projections.',
        'Assist senior leadership in due diligence and portfolio reviews.',
        'Automate recurring reporting with modern BI tools.',
      ],
      requirements: [
        'B.Com / BBA / MBA in Finance or related quantitative field.',
        'Strong analytical mindset and advanced spreadsheet modeling capabilities.',
      ],
      benefits: [
        'Comprehensive medical insurance (₹3 Lakh cover)',
        'Sponsorship for CFA / professional certifications',
      ],
    ),
    Job(
      id: 'job-7',
      title: 'Junior Mobile App Developer (Flutter)',
      company: 'AppVenture Studio',
      companyLogoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150',
      location: 'Mumbai, Maharashtra (Hybrid)',
      categoryId: 'dev',
      salary: '₹3.5 - ₹5.5 LPA',
      jobType: 'Full Time',
      workplaceType: 'Hybrid',
      experienceLevel: 'Entry (0-2 yrs)',
      postedAgo: '3 days ago',
      isFeatured: false,
      cardColor: Color(0xFF1E3A8A),
      skills: ['Flutter', 'Dart', 'Git', 'OOP', 'UI Design'],
      description:
          'A fantastic opportunity for an enthusiastic junior developer to learn from experienced leads while delivering consumer-facing applications in Flutter.',
      responsibilities: [
        'Implement UI screens according to Figma designs.',
        'Fix bugs and perform unit/widget tests.',
        'Learn and adopt modern Flutter architecture.',
      ],
      requirements: [
        'Knowledge of Flutter & Dart fundamentals.',
        'Good grasp of object-oriented programming and data structures.',
        'Eager to learn and accept constructive code review feedback.',
      ],
      benefits: [
        'Fast-track career mentorship and guided learning',
        'Hybrid schedule with flexible timings',
        'Annual ₹15,000 learning stipend (Coursera / Udemy)',
      ],
    ),
    Job(
      id: 'job-8',
      title: 'Brand & Graphic Designer',
      company: 'Creative Hive Co.',
      companyLogoUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=150',
      location: 'Chennai, Tamil Nadu / Remote',
      categoryId: 'design',
      salary: '₹4.5 - ₹7 LPA',
      jobType: 'Contract',
      workplaceType: 'Remote',
      experienceLevel: 'Mid Level (2-4 yrs)',
      postedAgo: '4 days ago',
      isFeatured: false,
      cardColor: Color(0xFF581C87),
      skills: ['Illustrator', 'Photoshop', 'Typography', 'Brand Identity', 'Motion Graphics'],
      description:
          'Help shape the visual identity of progressive tech brands through iconic typography, logo systems, and visual narratives.',
      responsibilities: [
        'Create brand identity packages, vector iconography, and marketing collateral.',
        'Design social media graphics, presentation decks, and packaging.',
      ],
      requirements: [
        '2+ years in branding and graphic design with an eye-catching portfolio.',
        'Proficiency in Adobe Creative Cloud Suite.',
      ],
      benefits: [
        'Contract with high probability of permanent conversion',
        'Creative freedom and diverse client accounts',
      ],
    ),
  ];

  static List<JobApplication> sampleApplications = [
    JobApplication(
      id: 'app-101',
      jobId: 'job-1',
      jobTitle: 'Senior Flutter Developer',
      company: 'TechNova Solutions',
      applicantName: 'Raju Patel',
      email: 'raju.patel@example.com',
      phone: '+91 98765 43210',
      portfolioUrl: 'https://github.com/rajupatel',
      experienceLevel: '3-5 years',
      educationLevel: 'Bachelor Degree',
      workPreference: 'Remote',
      immediatelyAvailable: true,
      willingToRelocate: false,
      subscribeAlerts: true,
      selectedSkills: ['Flutter', 'Dart', 'State Management'],
      coverLetter: 'Excited to contribute to high performance cross-platform applications!',
      appliedAt: DateTime.now().subtract(const Duration(days: 2)),
      status: 'Under Review',
    ),
    JobApplication(
      id: 'app-102',
      jobId: 'job-3',
      jobTitle: 'Cloud Solutions Architect',
      company: 'DataFlow Systems',
      applicantName: 'Rohan Verma',
      email: 'rohan.verma@example.com',
      phone: '+91 98123 45678',
      portfolioUrl: 'https://github.com/rohanverma',
      experienceLevel: '5+ years',
      educationLevel: 'Master Degree',
      workPreference: 'Hybrid',
      immediatelyAvailable: true,
      willingToRelocate: true,
      subscribeAlerts: true,
      selectedSkills: ['AWS', 'Kubernetes', 'Docker', 'CI/CD'],
      coverLetter: 'Passionate about building scalable cloud architectures and robust microservices.',
      appliedAt: DateTime.now().subtract(const Duration(days: 4)),
      status: 'Shortlisted',
    ),
    JobApplication(
      id: 'app-103',
      jobId: 'job-4',
      jobTitle: 'Product Design Lead',
      company: 'PixelCraft Studio',
      applicantName: 'Soham Deshmukh',
      email: 'soham.deshmukh@example.com',
      phone: '+91 97654 32109',
      portfolioUrl: 'https://github.com/sohamdesign',
      experienceLevel: '5+ years',
      educationLevel: 'Bachelor Degree',
      workPreference: 'Remote',
      immediatelyAvailable: false,
      willingToRelocate: false,
      subscribeAlerts: true,
      selectedSkills: ['Figma', 'User Research', 'Design Systems'],
      coverLetter: 'Looking forward to creating user-centric and accessible enterprise products.',
      appliedAt: DateTime.now().subtract(const Duration(days: 6)),
      status: 'Submitted',
    ),
  ];
}
